### PR TITLE
package: bump to base-x 1.1.0

### PR DESCRIPTION
**Pull request by dcousens**
Going to merge/publish as soon as tests pass

### CODE REVIEW

**Comment by dcousens** [comment]
ping @jprichardson or not, looks like you need to publish :laughing:

**Comment by jprichardson** [comment]
> ping @jprichardson or not, looks like you need to publish 

Looks like `base-x@1.1.0` hasn't been published, no? I see `1.0.4` as the latest?

**Comment by dcousens** [comment]
> base-x   dcousens
Fast base encoding / decoding of any given alphabet
70   v1.1.0

> arch| ~/workspace/test$ npm i base-x
/home/daniel/workspace/test
└── base-x@1.1.0

I see what you mean though,  on https://www.npmjs.com/package/base-x it says `v1.0.4`.

**Comment by jprichardson** [comment]
> I see what you mean though, on https://www.npmjs.com/package/base-x it says v1.0.4.

Yep, this is weird. Any idea why it's showing `1.0.4` still?

Done.

**Comment by dcousens** [comment]
@jprichardson `npm` is incredibly stable software.

https://www.npmjs.com/package/bs*

**Pull request merged**
