### PR TITLE
Release v4.0.1

### PR DESCRIPTION
**Pull request by dcousens**
Needs merge + release.

I would do it automatically,  but I'm not on the `npm` package.

### CODE REVIEW

**Comment by dcousens** [comment]
ping @jprichardson

**Comment by fanatid** [comment]
I think will better if JP run `npm owner add dcousens` in project directory :)

**Comment by jprichardson** [comment]
Added you both. Sorry guys.

**Comment by dcousens** [comment]
Published as `v4.0.1`

**Pull request merged**
