### PR TITLE
rm lib/, use index.js

### PR DESCRIPTION
**Pull request by dcousens**
Any reason to use `lib/`?  I've only ever seen it in transpiled libraries,  so seeing it here confused me a little bit.
Even more confusing is its presence in such a simple module.

Not really an issue though,  so feel free to reject if you feel this isn't necessary.

### CODE REVIEW

**Comment by jprichardson** [comment]
> Any reason to use lib/? I've only ever seen it in transpiled libraries, so seeing it here confused me a little bit.

I'd be willing to be that at least 50% of the top 50 npm libraries use `lib` for a directory. Regardless, switching to `index.js` is fine.

**Comment by dcousens** [comment]
:+1:  I guess I need to diversify,  I haven't seen an instance of that in several months.

**Comment by jprichardson** [comment]
I've actually been thinking a bit about this since I've been transpiling with babel... for S&G's...

From what I checked:

Use `lib`:
- https://github.com/request/request
- https://github.com/mochajs/mocha
- https://github.com/caolan/async
- https://github.com/strongloop/express
- https://github.com/Marak/colors.js

Didn't use `lib`:
- `lodash`
- `through2`
- `mkdirp`
- `commander`
- `debug`

When I wrote CoffeeScript, I use to transpile from `src/` to `lib/`.... but when I started JavaScript, I started just using `lib/`. Lately, I prefer just putting everything in `index.js` or as much as possible...

**Comment by jprichardson** [comment]
** cough **

- https://github.com/indutny/bn.js
- https://github.com/indutny/elliptic

> I guess I need to diversify, I haven't seen an instance of that in several months.

@dcousens Aren't you a collaborator on both of these projects?

**Comment by dcousens** [comment]
Haha.  I guess in that sense `bn.js` is already ready for browser.  1 file and all that.
As for elliptic,  ha.  Woops.

**Pull request merged**
